<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\YdcViewer.Dicom\YdcViewer.Dicom.csproj" />
    <ProjectReference Include="..\YdcViewer.Renderer\YdcViewer.Renderer.csproj" />
    <ProjectReference Include="..\YdcViewer.Auth\YdcViewer.Auth.csproj" />
    <ProjectReference Include="..\YdcViewer.Data\YdcViewer.Data.csproj" />
  </ItemGroup>

</Project>
